/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardUserRouteImport } from './routes/dashboard.user'
import { Route as DashboardVendorRouteImport } from './routes/dashboard.vendor'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProfileAdminRouteImport } from './routes/profile.admin'
import { Route as ProfileUserRouteImport } from './routes/profile.user'
import { Route as ProfileVendorRouteImport } from './routes/profile.vendor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVendorRoute = DashboardVendorRouteImport.update({
  id: '/dashboard/vendor',
  path: '/dashboard/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAdminRoute = ProfileAdminRouteImport.update({
  id: '/profile/admin',
  path: '/profile/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserRoute = ProfileUserRouteImport.update({
  id: '/profile/user',
  path: '/profile/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVendorRoute = ProfileVendorRouteImport.update({
  id: '/profile/vendor',
  path: '/profile/vendor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customize': typeof CustomizeRoute
  '/exchange': typeof ExchangeRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/admin': typeof ProfileAdminRoute
  '/profile/user': typeof ProfileUserRoute
  '/profile/vendor': typeof ProfileVendorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customize': typeof CustomizeRoute
  '/exchange': typeof ExchangeRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/admin': typeof ProfileAdminRoute
  '/profile/user': typeof ProfileUserRoute
  '/profile/vendor': typeof ProfileVendorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customize': typeof CustomizeRoute
  '/exchange': typeof ExchangeRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/admin': typeof ProfileAdminRoute
  '/profile/user': typeof ProfileUserRoute
  '/profile/vendor': typeof ProfileVendorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customize'
    | '/exchange'
    | '/sell'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/dashboard/vendor'
    | '/product/$id'
    | '/profile/admin'
    | '/profile/user'
    | '/profile/vendor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customize'
    | '/exchange'
    | '/sell'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/dashboard/vendor'
    | '/product/$id'
    | '/profile/admin'
    | '/profile/user'
    | '/profile/vendor'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customize'
    | '/exchange'
    | '/sell'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/dashboard/vendor'
    | '/product/$id'
    | '/profile/admin'
    | '/profile/user'
    | '/profile/vendor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomizeRoute: typeof CustomizeRoute
  ExchangeRoute: typeof ExchangeRoute
  SellRoute: typeof SellRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  VendorsRoute: typeof VendorsRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardVendorRoute: typeof DashboardVendorRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileAdminRoute: typeof ProfileAdminRoute
  ProfileUserRoute: typeof ProfileUserRoute
  ProfileVendorRoute: typeof ProfileVendorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vendor': {
      id: '/dashboard/vendor'
      path: '/dashboard/vendor'
      fullPath: '/dashboard/vendor'
      preLoaderRoute: typeof DashboardVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/admin': {
      id: '/profile/admin'
      path: '/profile/admin'
      fullPath: '/profile/admin'
      preLoaderRoute: typeof ProfileAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/user': {
      id: '/profile/user'
      path: '/profile/user'
      fullPath: '/profile/user'
      preLoaderRoute: typeof ProfileUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/vendor': {
      id: '/profile/vendor'
      path: '/profile/vendor'
      fullPath: '/profile/vendor'
      preLoaderRoute: typeof ProfileVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CustomizeRoute: CustomizeRoute,
  ExchangeRoute: ExchangeRoute,
  SellRoute: SellRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  VendorsRoute: VendorsRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardVendorRoute: DashboardVendorRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileAdminRoute: ProfileAdminRoute,
  ProfileUserRoute: ProfileUserRoute,
  ProfileVendorRoute: ProfileVendorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
